name: tensorcraft
version: git
version-script: git describe --tags

architectures:
  - build-on: [amd64]
    run-on: [amd64]

summary: Server for Keras models
description: |
  The Polynome is a HTTP server that serves Keras models using TensorFlow
  runtime.

base: core18
grade: devel
confinement: devmode

parts:
  tensorcraft:
    plugin: python
    python-version: python3
    source: .

apps:
  tensorcraft:
    daemon: simple
    stop-timeout: 10s
    command: bin/tensorcraft server
